server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://192.168.99.100:5430/demoDB
    username: usr
    password: pwd
  flyway:
    url: jdbc:postgresql://192.168.99.100:5430/demoDB
    user: usr
    password: pwd

room:
  showAllId: 1408

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
